C:\Users\cruzf\wrk_django_rest_api\recipe-app-api>docker-compose run app sh -c "python manage.py test"
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..
----------------------------------------------------------------------
Ran 2 tests in 0.001s

OK
Destroying test database for alias 'default'...

C:\Users\cruzf\wrk_django_rest_api\recipe-app-api>
